from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
from time import  sleep
import os,sys

class Login():
    #登录
    def user_login(self,driver,txtUsername,txtPassword):
        driver.find_element_by_xpath(".//*[@id='txtUsername']").clear()
        driver.find_element_by_xpath(".//*[@id='txtUsername']").send_keys(txtUsername)
        driver.find_element_by_xpath(".//*[@id='txtPassword']").clear()
        driver.find_element_by_xpath(".//*[@id='txtPassword']").send_keys(txtPassword)
        driver.find_element_by_xpath("//*[@id='btnLogin']").click()
    #教师管理
    def user_teachermanager(self,driver,teacherName,teacherPhone,teacherEmail,teacherWechat,teacherQQ):
        sleep(2)
        above1=driver.find_element_by_xpath("//*[@id='img_userPhoto']")
        ActionChains(driver).move_to_element(above1).perform()
        sleep(5)
        driver.find_element_by_xpath("//*[@id='header']/div[1]/div/div[4]/ul/li[1]/a").click()
        driver.find_element_by_xpath(".//*[@id='btnAdd']").click()
        frame_ele=driver.find_element_by_xpath(".//iframe[@class='jzart-iframe']")
        driver.switch_to.frame(frame_ele)
        sleep(2)
        driver.find_element_by_xpath(".//*[@id='teacherName']").send_keys(teacherName)
        driver.find_element_by_xpath(".//*[@id='teacherSex']/label[2]/i").click()
        #选择省份
        driver.find_element_by_xpath(".//*[@class='schoolSelect']/ul[1]/li[10]/a").click()
        js="var action=document.documentElement.scrollTop=10000"
        driver.execute_script(js)
        #通过拖动滚动条，选择学校
        driver.find_element_by_xpath(".//*[@class='schoolSelect']/ul[2]/li[24]/a").click()
        driver.find_element_by_xpath(".//*[@id='teacherPhone']").send_keys(teacherPhone)
        driver.find_element_by_xpath(".//*[@id='teacherPwd']").send_keys("1")
        driver.find_element_by_xpath(".//*[@id='teacherEmail']").send_keys(teacherEmail)
        driver.find_element_by_xpath(".//*[@id='teacherWechat']").send_keys(teacherWechat)
        driver.find_element_by_xpath(".//*[@id='teacherQQ']").send_keys(teacherQQ)
        driver.find_element_by_xpath(".//*[@id='btnSave']").click()
        sleep(2)
        driver.switch_to.default_content()
        driver.refresh()
    #退出
    def user_logout(self,driver):
        sleep(2)
        above1=driver.find_element_by_xpath("//*[@id='img_userPhoto']")
        ActionChains(driver).move_to_element(above1).perform()
        sleep(5)
        driver.find_element_by_xpath("//*[@id='header']/div[1]/div/div[4]/ul/li[4]/a").click()




    #诊断工具管理
    def user_toolmanage(self,driver,toolName,toolSynopsis,num,input):
         sleep(2)
         driver.find_element_by_xpath("//*[@id='header']/div[2]/div[2]/a[2]").click()
         sleep(2)
         driver.find_element_by_xpath(".//*[@id='btnAdd']").click()
         frame_ele=driver.find_element_by_xpath(".//iframe[@class='jzart-iframe']")
         driver.switch_to.frame(frame_ele)
         sleep(2)
         driver.find_element_by_xpath(".//*[@id='toolName']").send_keys(toolName)
         driver.find_element_by_xpath(".//*[@id='toolSynopsis']").send_keys(toolSynopsis)
         sleep(2)
         driver.find_element_by_xpath(".//*[@class='fileHover fileBtn']").click()
         curpath = os.path.dirname(os.path.realpath(__file__))
         picexe = os.path.join(curpath, "Chrome_UploadPic_Para.exe") + " " + os.path.join(curpath, "1.jpg")
         os.system(picexe)
         # pic_path ="{}\\1.jpg".format(sys.path[0])
         # os.system(r'C:\Users\Administrator\PycharmProjects\KesgoTD_Backstage\Chrome_UploadPic_Para.exe {}'.format(pic_path))
         # os.system('C:\\Users\\Administrator\\PycharmProjects\\KesgoTD_Backstage\\Chrome_UploadPic_Para.exe {}'.format(pic_path))
         # os.system("C:\\Users\\Administrator\\PycharmProjects\\KesgoTD_Backstage\\Chrome_UploadPic_Para.exe {}".format(pic_path))
         sleep(4)
         #针对工具模块为2-7的情况
         for j in range(num):
                if j<2:
                   js="var action=document.documentElement.scrollTop=10000"
                   driver.execute_script(js)
                   driver.find_element_by_xpath(".//*[@id='form']/table/tbody[{}]/tr/td/input".format(j+2)).send_keys(input+str(j))
                else:
                   driver.find_element_by_xpath(".//*[@id='btnSave']").click()
                   js="var action=document.documentElement.scrollTop=10000"
                   driver.execute_script(js)
                   driver.find_element_by_xpath(".//*[@id='form']/table/tbody[{}]/tr/td/input".format(j+2)).send_keys(input+str(j))
                sleep(3)
         driver.find_element_by_xpath(".//*[@id='isEdit']/label[2]").click()
         driver.find_element_by_xpath(".//*[@class='u-button f-clorg']").click()
    #课程管理-新建课程
    def  user_addcourse(self,driver,courseName):
         sleep(2)
         driver.find_element_by_xpath("//*[@id='header']/div[2]/div[2]/a[1]").click()
         sleep(2)
         driver.find_element_by_xpath("/html/body/form/div[2]/div/div[3]/div[1]/div/i").click()
         frame_ele=driver.find_element_by_xpath(".//iframe[@class='jzart-iframe']")
         driver.switch_to.frame(frame_ele)
         sleep(2)
         driver.find_element_by_xpath(".//*[@id='courseName']").send_keys(courseName)
         driver.find_element_by_xpath(".//*[@id='courseType']/label[1]/i").click()
         driver.find_element_by_xpath("//*[@id='templateUpload_1']/a").click()
         curpath = os.path.dirname(os.path.realpath(__file__))
         picexe = os.path.join(curpath, "Chrome_UploadPic_Para.exe") + " " + os.path.join(curpath, "1.jpg")
         os.system(picexe)
         # pic_path ="{}\\1.jpg".format(sys.path[0])
         # os.system(r'C:\Users\Administrator\PycharmProjects\KesgoTD_Backstage\Chrome_UploadPic_Para.exe {}'.format(pic_path))
         driver.find_element_by_xpath(".//*[@id='saveBtn']").click()
         driver.switch_to.default_content()
         sleep(2)
    #课程管理-定位课程的位置，以便修改对应课程下的章节、微课、案例，定位课程的位置
    def user_coursecur(self,driver):
         sleep(2)
         driver.find_element_by_xpath("/html/body/form/div[2]/div/div[3]/div[2]/div/div/a[2]/img").click()
         # driver.find_element_by_xpath(".//*[@class='m-nav']/li[3]/a").click()
    #课程管理-章节管理
    def  user_chaptermanagement(self,driver,course_nav,num,capterName):
         sleep(2)
         driver.find_element_by_xpath(".//*[@class='m-leftBar']/a[3]").click()
         sleep(4)
         driver.find_element_by_xpath("/html/body/form/div[2]/div/div[2]/div[2]/div[2]/table/tbody/tr/td/button").click()
         driver.find_element_by_xpath("/html/body/form/div[2]/div/div[2]/div[2]/div[2]/table/tbody/tr[1]/td/div[1]/input").clear()
         driver.find_element_by_xpath("/html/body/form/div[2]/div/div[2]/div[2]/div[2]/table/tbody/tr[1]/td/div[1]/input").send_keys(course_nav)
         driver.find_element_by_xpath("/html/body/form/div[2]/div/div[2]/div[2]/div[2]/div[2]/a").click()
         sleep(3)
         #N个章节的循环方法
         # for j in range(num):
         #        driver.find_element_by_xpath(".//button[@class='fileBtn']").click()
         #        driver.find_element_by_xpath(".//*[@id='capterName']").send_keys(capterName+str(j))
         #        driver.find_element_by_xpath(".//*[@class='m-tableform']/tbody/tr[{}]/td/div[2]/i[1]".format(j+2)).click()
         #        sleep(3)
    #课程管理-微课管理
    def  user_microclassmanagement(self,driver,microName):
         sleep(2)
         driver.find_element_by_xpath(".//*[@class='m-leftBar']/a[1]").click()
         sleep(4)
         driver.find_element_by_xpath(".//*[@class='m-leftBar']/a[2]").click()
         sleep(4)
         driver.find_element_by_xpath(".//*[@class='u-button u-small f-corg']").click()
         frame_ele=driver.find_element_by_xpath(".//iframe[@class='jzart-iframe']")
         driver.switch_to.frame(frame_ele)
         sleep(4)
         driver.find_element_by_xpath(".//*[@id='microName']").send_keys(microName)
         sleep(4)
         driver.find_element_by_xpath(".//*[@id='microEdit']/table/tbody/tr[2]/td/div/div/div[1]/label").click()
         driver.find_element_by_xpath(".//*[@id='microEdit']/table/tbody/tr[2]/td/div/div/div[2]/ul/li[1]/a").click()
         driver.find_element_by_xpath(".//*[@class='fileHover fileBtn']").click()
         curpath = os.path.dirname(os.path.realpath(__file__))
         filexe = os.path.join(curpath, "Chrome_UploadFile_Para.exe") + " " + os.path.join(curpath, "docx.docx")
         os.system(filexe)
         # file_path ="{}\\docx.docx".format(sys.path[0])
         # os.system(r'C:\Users\Administrator\PycharmProjects\KesgoTD_Backstage\Chrome_UploadFile_Para.exe {}'.format(file_path))
         driver.find_element_by_xpath(".//*[@id='saveBtn']").click()
         driver.switch_to.default_content()
         sleep(2)
    #课程管理-案例管理
    def  user_casemanagement(self,driver,caseName,txtCaseDesc,body,num,textarea,biaotinum,input,xuanxiang,txtDiscussQues,body1,txtDiagnoseQues,body2):
         sleep(2)
         driver.find_element_by_xpath(".//*[@class='m-leftBar']/a[1]").click()
         sleep(4)
         driver.find_element_by_xpath(".//*[@class='u-button u-small f-corg']").click()
         driver.find_element_by_xpath(".//*[@id='caseName']").send_keys(caseName)
         driver.find_element_by_xpath(".//*[@id='chooseMicro']").click()
         frame_ele=driver.find_element_by_xpath(".//iframe[@class='jzart-iframe']")
         driver.switch_to.frame(frame_ele)
         sleep(2)
         driver.find_element_by_xpath(".//*[@id='radio0']").click()
         driver.find_element_by_xpath(".//*[@id='saveBtn']").click()
         driver.switch_to.default_content()
         sleep(2)
         driver.find_element_by_xpath(".//table[@class='m-tableform']/tbody[1]/tr[4]/td/div/a").click()
         curpath = os.path.dirname(os.path.realpath(__file__))
         picexe = os.path.join(curpath, "Chrome_UploadPic_Para.exe") + " " + os.path.join(curpath, "1.jpg")
         os.system(picexe)
         # pic_path ="{}\\1.jpg".format(sys.path[0])
         # os.system(r'C:\Users\Administrator\PycharmProjects\KesgoTD_Backstage\Chrome_UploadPic_Para.exe {}'.format(pic_path))
         driver.find_element_by_xpath(".//*[@id='txtCaseDesc']").send_keys(txtCaseDesc)
         js="var action=document.documentElement.scrollTop=10000"
         driver.execute_script(js)
         sleep(2)
         driver.switch_to.frame(0)
         sleep(2)
         driver.find_element_by_xpath("/html/body").click()
         driver.find_element_by_xpath("/html/body").send_keys(body)
         driver.switch_to.default_content()
         sleep(2)
         driver.find_element_by_xpath(".//*[@id='caseVideoUpload_1']/a").click()
         curpath = os.path.dirname(os.path.realpath(__file__))
         videoexe = os.path.join(curpath, "Chrome_UploadVideo_Para.exe") + " " + os.path.join(curpath, "video.mp4")
         os.system(videoexe)
         # pic_path ="{}\\video.mp4".format(sys.path[0])
         # os.system(r'C:\Users\Administrator\PycharmProjects\KesgoTD_Backstage\Chrome_UploadVideo_Para.exe {}'.format(pic_path))
         #思考题开放题
         for j in range(num):
                js="var action=document.documentElement.scrollTop=10000"
                driver.execute_script(js)
                driver.find_element_by_xpath(".//*[@class='m-tableform']/tbody[3]/tr/td/button[1]").click()
                driver.find_element_by_xpath(".//*[@class='m-tableform']/tbody[2]/tr[{}]/td/div/div/textarea".format(j+1)).send_keys(textarea+str(j))
                sleep(3)
         js="var action=document.documentElement.scrollTop=10000"
         driver.execute_script(js)
         #思考题投票题
         for t in range(biaotinum):
                driver.find_element_by_xpath(".//*[@class='m-tableform']/tbody[3]/tr/td/button[2]").click()
                js="var action=document.documentElement.scrollTop=10000"
                driver.execute_script(js)
                driver.find_element_by_xpath(".//*[@id='policycase']/table/tbody[2]/tr[{}]/td/div/div/table/tbody/tr[1]/td/input".format(t+biaotinum+1)).send_keys(input+str(t))
                js="var action=document.documentElement.scrollTop=10000"
                driver.execute_script(js)
                for k in range(4):
                         driver.find_element_by_xpath(".//*[@id='policycase']/table/tbody[2]/tr[{0}]/td/div/div/table/tbody/tr[2]/td/table/tbody/tr[{1}]/td[1]/input".format(t+biaotinum+1,k+1)).send_keys(xuanxiang+str(k))
                sleep(3)
         driver.find_element_by_xpath(".//*[@id='caseReadUpload_1']/a").click()
         curpath = os.path.dirname(os.path.realpath(__file__))
         filexe = os.path.join(curpath, "Chrome_UploadFile_Para.exe") + " " + os.path.join(curpath, "docx.docx")
         os.system(filexe)
         # file_path ="{}\\docx.docx".format(sys.path[0])
         # os.system(r'C:\Users\Administrator\PycharmProjects\KesgoTD_Backstage\Chrome_UploadFile_Para.exe {}'.format(file_path))
         driver.find_element_by_xpath(".//*[@class='u-button f-clorg']").click()
         sleep(2)
         js="var action=document.documentElement.scrollTop=0"
         driver.execute_script(js)
         driver.find_element_by_xpath(".//*[@id='txtDiscussQues']").send_keys(txtDiscussQues)
         sleep(6)
         driver.find_element_by_xpath(".//*[@id='chooseDiagnose']").click()
         frame_ele=driver.find_element_by_xpath(".//iframe[@class='jzart-iframe']")
         driver.switch_to.frame(frame_ele)
         sleep(2)
         driver.find_element_by_xpath(".//*[@id='radio0']").click()
         driver.find_element_by_xpath(".//*[@id='nextBtn']").click()
         driver.find_element_by_xpath(".//*[@id='saveBtn']").click()
         sleep(6)
         driver.switch_to.default_content()
         sleep(2)
         driver.switch_to.frame(0)
         sleep(2)
         driver.find_element_by_xpath("/html/body").click()
         driver.find_element_by_xpath("/html/body").send_keys(body1)
         driver.switch_to.default_content()
         sleep(6)
         js="var action=document.documentElement.scrollTop=10000"
         driver.execute_script(js)
         driver.find_element_by_xpath(".//*[@id='txtDiagnoseQues']").send_keys(txtDiagnoseQues)
         sleep(2)
         driver.switch_to.frame(1)
         sleep(2)
         driver.find_element_by_xpath("html/body").click()
         driver.find_element_by_xpath("html/body").send_keys(body2)
         driver.switch_to.default_content()
         sleep(4)
         driver.find_element_by_xpath(".//*[@id='fileUpload_1']/a").click()
         curpath = os.path.dirname(os.path.realpath(__file__))
         filexe = os.path.join(curpath, "Chrome_UploadFile_Para.exe") + " " + os.path.join(curpath, "ppt.ppt")
         os.system(filexe)
         # file_path ="{}\\ppt.ppt".format(sys.path[0])
         # os.system(r'C:\Users\Administrator\PycharmProjects\KesgoTD_Backstage\Chrome_UploadFile_Para.exe {}'.format(file_path))
         driver.find_element_by_xpath(".//*[@class='u-button f-clorg']").click()


#教师登录
class TeachLogin():
    def user_login(self,driver,txtUsername,txtPassword):
        driver.find_element_by_id("txtUsername").clear()
        driver.find_element_by_id("txtUsername").send_keys(txtUsername)
        driver.find_element_by_id("txtPassword").clear()
        driver.find_element_by_id("txtPassword").send_keys(txtPassword)
        driver.find_element_by_id("btnLogin").click()

    def user_classmanage(self,driver,className):
         # driver.refresh()
         sleep(3)
         above=driver.find_element_by_xpath("/html/body/form/div[1]/div[1]/div/div[5]/p")
         ActionChains(driver).move_to_element(above).perform()
         sleep(5)
         driver.find_element_by_xpath("//*[@id='header']/div[1]/div/div[5]/ul/li[1]/a").click()
         sleep(4)
         driver.find_element_by_xpath("/html/body/form/div[2]/div/div[3]/a").click()
         frame_ele=driver.find_element_by_xpath(".//iframe[@class='jzart-iframe']")
         driver.switch_to.frame(frame_ele)
         sleep(2)
         driver.find_element_by_xpath(".//*[@id='className']").send_keys(className)
         sleep(4)
         driver.find_element_by_xpath(".//*[@id='saveBtn']").click()
         driver.switch_to.default_content()
         sleep(4)
         driver.find_element_by_xpath(".//*[@class='f-right m-iconoper']/a[3]").click()
         frame_ele=driver.find_element_by_xpath(".//iframe[@class='jzart-iframe']")
         driver.switch_to.frame(frame_ele)
         sleep(2)
         driver.find_element_by_xpath(".//*[@class='fileHover fileBtn']").click()
         curpath = os.path.dirname(os.path.realpath(__file__))
         filexe = os.path.join(curpath, "Chrome_UploadFile_Para.exe") + " " + os.path.join(curpath, "student.xls")
         os.system(filexe)
         # file_path ="{}\\student.xls".format(sys.path[0])
         # os.system(r'C:\Users\Administrator\PycharmProjects\KesgoTD_Backstage\Chrome_UploadFile_Para.exe {}'.format(file_path))
         sleep(3)
         driver.find_element_by_xpath(".//*[@class='u-button f-clorg']").click()
         driver.switch_to.default_content()
         sleep(3)

    def user_experimentmanager(self,driver,expName):
         sleep(3)
         driver.find_element_by_xpath(".//*[@name='tab03']").click()
         sleep(3)
         driver.find_element_by_xpath(".//*[@id='btnAdd']").click()
         driver.find_element_by_xpath(".//*[@class='dropdown-toggle']/label").click()
         driver.find_element_by_xpath(".//*[@class='scroll-list-wrap']/ul/li/a").click()
         driver.find_element_by_xpath(".//*[@id='expName']").send_keys(expName)
         sleep(3)
         # driver.find_element_by_xpath("/html/body/form/div[2]/div/div[2]/table/tbody/tr[3]/td/div/span/i").click()
         driver.find_element_by_xpath(".//*[@id='btnChooseCase']").click()
         frame_ele=driver.find_element_by_xpath(".//iframe[@class='jzart-iframe']")
         driver.switch_to.frame(frame_ele)
         sleep(3)
         driver.find_element_by_xpath(".//*[@id='radio0']").click()
         driver.find_element_by_xpath(".//*[@id='saveBtn']").click()
         driver.switch_to.default_content()
         sleep(3)
         driver.find_element_by_xpath("/html/body/form/div[2]/div/div[2]/table/tbody/tr[3]/td/div/span/i").click()
         sleep(3)
         driver.find_element_by_xpath(".//*[@id='btnSave']").click()
         sleep(2)
         driver.find_element_by_xpath("/html/body/form/div[2]/div/div[1]/div[2]/div/div/div[2]/a").click()
         sleep(2)
         driver.find_element_by_xpath(".//*[starts-with(@id,'jzartok')]").click()
         # driver.switch_to.frame(frame_ele)
         # driver.find_element_by_xpath(".//*[@id='jzartok3027']").click()
         # driver.switch_to.default_content()

    def user_logout(self,driver):
         driver.refresh()
         sleep(2)
         above=driver.find_element_by_xpath("/html/body/form/div[1]/div[1]/div/div[5]/p")
         ActionChains(driver).move_to_element(above).perform()
         sleep(5)
         driver.find_element_by_xpath("//*[@id='header']/div[1]/div/div[5]/ul/li[4]/a").click()
         # above=driver.find_element_by_xpath("//*[@id='img_userPhoto']")
         # ActionChains(driver).move_to_element(above).perform()
         # driver.find_element_by_xpath("//*[@id='header']/div[1]/div/div[5]/ul/li[4]/a").click()

if __name__ == '__main__':
        pic_path ="{}\\1.jpg".format(sys.path[0])
        a = r'C:\Users\Administrator\PycharmProjects\KesgoTD_Backstage\Chrome_UploadPic_Para.exe {}'.format(pic_path)
        print(a)
        curpath = os.path.dirname(os.path.realpath(__file__))
        exer = os.path.join(curpath, "Chrome_UploadPic_Para.exe") + " " + os.path.join(curpath, "1.jpg")
        print(exer)